version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-redgio-5-participant-connector
    ports:
      - "3000:3000"
    environment:
      APP_NAME: data-connector
      APP_PORT: 3000
      APP_LOG_LEVEL: debug
      DB_NAME: data-connector
      DB_HOST: postgres
      DB_PORT: 6432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      KC_URL: http://localhost:9090
      KC_REALM: data-connector
      KC_CLIENT_ID: local-connector
      KC_CLIENT_SECRET: JF9nTM1alqbOc6RDMSelKhKxAukojDRT

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: connector
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "9090:8080"
    command: start-dev
    depends_on:
      - postgres

volumes:
  postgres_data:
  minio_data:
